# Generated by Django 5.2.7 on 2025-10-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('code_direction', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_direction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('num_partenaire', models.AutoField(primary_key=True, serialize=False)),
                ('nom_partenaire', models.CharField(max_length=100)),
                ('prenom_partenaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCourrier',
            fields=[
                ('num_type_courrier', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_type_courrier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code_service', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=100)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='courrier_UNA.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Destinataire',
            fields=[
                ('num_destinataire', models.AutoField(primary_key=True, serialize=False)),
                ('prenom_destinataire', models.CharField(max_length=100)),
                ('nom_destinataire', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='courrier_UNA.service')),
            ],
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('num_courrier', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_courrier', models.CharField(max_length=255)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers', to='courrier_UNA.destinataire')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers', to='courrier_UNA.partenaire')),
                ('type_courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers', to='courrier_UNA.typecourrier')),
            ],
        ),
    ]
