# Generated by Django 5.2.7 on 2025-10-17 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier_UNA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courriers', to='courrier_UNA.partenaire'),
        ),
    ]
